FROM --platform=linux/amd64 golang:1.22 AS build

WORKDIR /app
COPY . .

RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
    -ldflags="-w -s" \
    -o gold-admin-backend-linux-amd64 \
    main.go
